### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by rromanchuk** [jpetrich/HEVCDemo#1]
Before I start messing around with HEVC, do you know if this problem exists if you jump up the stack to `AVAssetExportSession`, and what about with `AVCaptureSession` 

```swift 
let session = AVCaptureSession()
session.sessionPreset = .hd4K3840x2160
```

curious if these are facing the same issue as well?

**Comment by jpetrich** [comment]
The issue seems to be that the default bit rate is different for H.264 and HEVC.  The default bit rate for H.264 is 5 mbit and the default bit rate for HEVC is 30 mbit.  If you set these manually, you will see performance consistent with other HEVC encoders.
